name: Publish Charms to latest/edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-charm:
    name: Publish Charm
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.source_branch }}

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.7.0
        with:
          credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          charm-path: ./
          channel: latest/edge
          charmcraft-channel: latest/stable
